### ISSUE TITLE
Lab Report 2 Feedback

### ISSUE THREAD

**Issue by TomlandHilarious** [katieki/cse15l-lab-reports#2]
Here is your feedback for Lab Report 2:

- [x] Correct screenshot of code diff page
- [ ] Correct failure inducing test file - 1
- [ ] Correct failure inducing test file - 2
- [ ] Correct failure inducing test file - 3
     - cannot see the test files' contents.
- [x] Screenshot of symptom output that caused the failure for test file - 1
- [x] Screenshot of symptom output that caused the failure for test file - 2
- [x] Screenshot of symptom output that caused the failure for test file - 3
- [x] Correct description for the relationship between the bug, the symptom, and the failure-inducing input for file - 1
- [x] Correct description for the relationship between the bug, the symptom, and the failure-inducing input for file - 2
- [x] Correct description for the relationship between the bug, the symptom, and the failure-inducing input for file - 3
- [x] Correct markdown formatting
- [x] Lab report is on its own page, not the index page
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:

Good job overall! But need to fix the test files so the contents of the test files can be displayed to the grader. We would recommend you to link to the markdown files
If you are going to submit a regrade request, please also respond to your github issue here when you submit a regrade request.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by katieki** [comment]
I tried leaving a link to the md file by adding the proper link format and putting .md instead of .html but it would be a link to the website. So I added screenshots of the problem inducing file under the faulty links instead.
